решение первой задачи 7-го модуля
js-tasks-ru/jsbasic-20201113_andrei78 pull request #9
Opened 2020-12-23 15:25 UTC by ratkevichnikita

2020-12-23 15:33 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 7-module/1-task/task.test.js — добавлен
```

2021-01-12 21:49 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Учебный проект: Лента-Меню
+ должна добавлять корневой элемент в свойство "elem"
+ должна отрисовать все кате��ории
+ при клике на кнопке "вперёд", должна прокрутить на 350px вперёд
+ при клике по кнопке "назад", должна прокрутить на 350px назад
+ после клика по ссылке, должно быть создано событие
+ созданное событие должно содержать в себе уникальный идентификатор товара ("id")
```
```diff
Учебный проект: Модальное окно
+ при вызове метода close(), вёрстка модального окна должна удаляться из body
+ при вызове метода close(), должен удаляться класс "is-modal-open" с элемента body
+ при клике по [X], должен удаляться класс "is-modal-open" с элемента body
+ при нажатии клавиши ESC, должен удаляться класс "is-modal-open" с элемента body
+ при нажатии клавиши ESC, вёрстка модального окна должна удаляться из body
+ при клике по [X], вёрстка модального окна должна удаляться из body
+ должен задавать заголовок модального окна
+ должна создавать основной элемент модального окна
+ должна создавать прозрачный фон
+ должна добавлять класс "is-modal-open" элементу body
+ должен вставлять содержимое модального окна в элемента с классом "modal__body"
```
```diff
Учебный проект: Пошаговый слайдер, часть 1
+ первый шаг должен быть активным
+ после создания должно быть нарисовано количество шагов, переданное в момент создания
+ должен перемещать ползунок
+ должен генерировать событие изменения значения
+ должен задавать ширину закрашиваемой области до ползунка
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2021-01-13 12:35 UTC, koalex requested changes
Исправь замечания

2021-01-13 12:35 UTC, koalex commented on 7-module/3-task/index.html
> +  <link rel="stylesheet" href="../../assets/styles/common.css" />
ты не должен менять путь, нужно использовать `live-server`

2021-01-13 12:35 UTC, koalex commented on 7-module/2-task/static.html
> +          <img src="../../assets/images/icons/cross-icon.svg" alt="close-icon" />
ты не должен менять путь, нужно использовать `live-server`

2021-01-13 12:35 UTC, koalex commented on 7-module/2-task/index.html
> +  <link rel="stylesheet" href="../../assets/styles/common.css" />
ты не должен менять путь, нужно использовать `live-server`

2021-01-13 12:35 UTC, koalex commented on 7-module/1-task/index.html
> +  <link rel="stylesheet" href="../../assets/styles/common.css" />
ты не должен менять путь, нужно использовать `live-server`

2021-01-13 12:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2021-01-21 15:52 UTC, koalex approved these changes

2021-01-21 15:53 UTC, merged